### PR TITLE
Add hbs, handlebars as markup syntax languages

### PR DESCRIPTION
**Pull request by Baltazore**
Hey I am pretty new neovim and language servers. 
I was trying to setyp emmet + nvim-cmp for quite some time now, and still having problems. The `emmet_ls` project just don't work properly. Your server doing good job on working with cmp, but can we add `hbs` as well ? 

Let me know what else needs to be done  to get this done

### CODE REVIEW

**Comment by pedro757** [comment]
This server uses the official emmet library that currently does not support hbs as you can see [here](https://github.com/emmetio/emmet/blob/451dbd69eca9829759872417aecfd9c0b21b4a27/src/config.ts#L280), however, you can work around changing your personal configuration [here](https://github.com/pedro757/emmet/blob/4bdb03230a66209e8e0f94fb19229a3622d2b690/README.md?plain=1#L39). Just add the filename you want to use. if you feel html emmets work with hbs, I don't know anything about handlebars.

**Comment by Baltazore** [comment]
I did change it in personal config, but it expands emmet snippet as css. I assumed I need to manually add handlebars to list of markup syntaxes.

Handlebars is just html with `{{ value }}` inserts and extra `{{if}}` or `{{each}}` loop

**Comment by pedro757** [comment]
It seems you're right. it expands as stylesheets emmets. Thank you for this pr.

**Comment by pedro757** [comment]
run this `npm update -g ls_emmet`

**Pull request merged**
